Repository GCE-NEIIST/GCE-NEIIST-webapp, pull requests merged in 2018-09, with the labels that each got.

#64 docs: updated README and added PR Template
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Category: Documentation

#71 Small UI and UX improvements on GCE-thesis
  angular-src/src/app/general/gce-thesis/gce-thesis.component.css
  angular-src/src/app/general/gce-thesis/gce-thesis.component.html
Labels: Category: User Interface

#73 Refactoring to leverage Continuous delivery
  angular-src/package-lock.json
  angular-src/package.json
  angular-src/src/app/app.module.ts
  angular-src/src/app/general/gce-thesis/gce-thesis.component.ts
  angular-src/src/app/general/login/login.component.ts
  angular-src/src/app/general/navbar/navbar.component.html
  angular-src/src/app/general/navbar/navbar.component.ts
  angular-src/src/app/services/auth-guard.service.ts
  angular-src/src/app/services/auth.service.ts
  angular-src/src/app/services/professor.service.spec.ts
  angular-src/src/app/services/professor.service.ts
  gce_base.js
  server/routes/student-routes.js
Labels: Type: Enhancement

#74 other: allows Continuous Delivery through Heroku
  package.json
Labels: Type: Bug: minor

#84 Fix production dependency error
  angular-src/package.json
  config/db.js
Labels: Type: Bug: minor
